### PR TITLE
MC1.17.1

### PR DESCRIPTION
**Pull request by oxodao**
I had to upgrade Gradle too, and since it's MC1.17, the required version of Java.

I needed this update for my server so I decided to try to upstream it ;)

### CODE REVIEW

**Comment by Chaos02** [comment]
hey - since 1.17 and 1.18 are very similar and 1.19 will also more or less only add a Mob - can you also port it to 1.18?
also happy new year :))
PS: dont really know my way around github yet but I guess I can somehow already get your changes before merge may happen - mind telling me how?

**Comment by oxodao** [comment]
@Chaos02 Hey!
I could definitly take a look at 1.18, shouldn't be too hard (If there is even anything to change at all). I'll check if I have free time in the upcoming days.

As for my current changes, you can clone this repository with the git command (Or simply download the zip) and you can build it with a simple `./gradlew build`. Be sure to clone my repository not the upstream one.

@LatvianModder Hey! Did you have the time to check this PR out by chance ?

**Comment by inverado** [comment]
Also came here to inquire about the mod being updated to 1.18+.

**Comment by oxodao** [comment]
@Chaos02 @inverado 

I planned on releasing my built jar directly but since there is no license on the Github repository and the Curseforge page only said "probably All rights reserved" I won't do it just to be sure I'm not breaking any license.

The 1.18 update seems a bit more complicated than I initially thought. I'm looking into it but I do not promise anything. 


Edit: nevermind, thanks to mcJty's guide it should be easy. Always doing great work, saved me a few time. Highly recommand his wiki

**Comment by oxodao** [comment]
Updated to 1.18.1: https://github.com/FTBTeam/FTB-Backups/pull/43

**Comment by MichaelHillcox** [comment]
Hay, thanks for this, we'll review your 1.18 version but at this point in time, we're not planning on releasing any official 1.17 versions of our mods as 1.17 has not recieved any LTS support from Forge. I'll close this for now but if we change our minds in the future, we'll review this again :+1:

**Pull request closed without merging**
